[tox]
envlist = py39, py3.10, py311, py312, py313, pypy3
skip_missing_interpreters = true

#[gh-actions]
#python =
#    3.8: py38
#    3.9: py39
#    3.10: py310
#    3.11: py311
#    3.12: py312
#    pypy3.10: pypy3

[testenv]
extras = dev

commands =
  {envpython} -m pytest {posargs:}
  {envpython} -m pylint cpplint.py
  {envpython} -m flake8 cpplint.py
