[tox]
envlist = py38, py39, py3.10, py311, py312, py313, pypy3
skip_missing_interpreters = true

[testenv]
extras = dev

commands =
  {envpython} -m pytest {posargs:}
  {envpython} -m pylint cpplint.py
